import type { VerificationQualitySnapshot } from '../domain'

export function qualitySnapshotFixture(): VerificationQualitySnapshot {
  return {
    schemaVersion: 'taxalens-verification-quality-snapshot:v1.1.0',
    capturedAt: '2026-07-16T19:00:00.000Z',
    campaign: {
      campaignId: 'flickr-quality-campaign',
      title: 'Flickr quality campaign',
      kind: 'flickr_target_verification',
      status: 'active',
      targetTaxon: {
        acceptedTaxonKey: 'gbif:1938069',
        scientificName: 'Papilio demoleus',
        commonName: 'Lime swallowtail',
        rank: 'species',
        authority: null,
      },
      sourceProviders: ['flickr'],
      samplingPlanId: 'flickr-quality-plan',
      samplingPurpose: 'quality_estimation',
      samplingDesign: 'stratified_random',
    },
    counts: {
      eligibleItems: 100,
      attemptedItems: 80,
      decisivelyReviewedItems: 60,
      decisiveQualitySampleItems: 60,
      correctQualitySampleItems: 57,
      errorQualitySampleItems: 3,
      unresolvedConflictItems: 2,
      adjudicatedItems: 1,
      anonymousReviewerCount: 4,
    },
    coverage: {
      schemaVersion: 'taxalens-verification-coverage:v1.0.0',
      eligibleItems: 100,
      attemptedItems: 80,
      unattemptedItems: 20,
      decisivelyReviewedItems: 60,
      resolvedYesItems: 57,
      resolvedNoItems: 3,
      uncertainItems: 8,
      mediaFailureItems: 4,
      deferredItems: 8,
      pendingItems: 20,
      effectiveReviewCount: 128,
      decisiveReviewCount: 112,
      yesReviewCount: 106,
      noReviewCount: 6,
      cantTellReviewCount: 8,
      cantViewReviewCount: 4,
      skippedReviewCount: 4,
      inspectedItems: 76,
      viewableItems: 72,
      reviewCoverage: 0.8,
      inspectionCoverage: 0.76,
      viewabilityRate: 72 / 76,
    },
    precision: {
      method: 'stratified_hajek',
      availability: 'available',
      estimateBlockers: [],
      pointEstimate: 0.95,
      intervalMethod: 'grouped_percentile_bootstrap',
      intervalAvailability: 'available',
      intervalBlockers: [],
      confidenceLevel: 0.95,
      interval: {
        lower: 0.91,
        upper: 0.98,
      },
      effectiveSampleSize: 54.4,
      decisiveSampleCount: 60,
      representedStrata: ['adult', 'larva'],
      strata: [
        {
          stratumId: 'adult',
          label: 'Adult',
          decisiveSampleCount: 50,
          populationWeight: 0.8,
          estimate: 0.96,
        },
        {
          stratumId: 'larva',
          label: 'Larva',
          decisiveSampleCount: 10,
          populationWeight: 0.2,
          estimate: 0.9,
        },
      ],
    },
    agreement: {
      pairwise: {
        availability: 'available',
        blockers: [],
        overlappingItemCount: 32,
        anonymousReviewerCount: 4,
        pairCount: 48,
        percentAgreement: 0.875,
      },
      nominalAlpha: {
        availability: 'available',
        blockers: [],
        overlappingItemCount: 32,
        alpha: 0.78,
      },
    },
    conflicts: {
      conflictedItems: 3,
      unresolvedConflictItems: 2,
      adjudicatedItems: 1,
      denominatorAttemptedItems: 80,
      conflictRate: 3 / 80,
    },
    referenceReadiness: {
      status: 'ready',
      blockers: [],
    },
    reviewedLabelLeakage: {
      status: 'passed',
      blockers: [],
    },
    referenceBank: {
      prototypeRoleAttestations: {
        status: 'verified_complete',
        providerSupportedRecordCount: 81,
        attestedRecordCount: 81,
        suitableRecordCount: 81,
        independentHumanTaxonomicVerificationClaimed: false,
      },
      taxonomicIdentityReviews: {
        reviewedRecordCount: 0,
        independentlyVerifiedRecordCount: 0,
      },
      prototypeSupportCount: 81,
      verifiedSupportCount: 0,
      excludedSupportCount: 12,
      conflicts: {
        availability: 'unavailable',
        conflictCount: null,
        unavailableReason:
          'No independently reviewed reference decision ledger is attached.',
      },
      providerDistribution: {
        availability: 'unavailable',
        entries: [],
        unavailableReason:
          'The aggregate prototype evidence does not publish provider counts.',
      },
      routeDistribution: {
        availability: 'available',
        entries: [
          { key: 'adult_field', label: 'Adult field', count: 80 },
          { key: 'larval', label: 'Larval', count: 1 },
          {
            key: 'pinned_specimen',
            label: 'Pinned specimen',
            count: 0,
          },
        ],
        unavailableReason: null,
      },
      readiness: {
        status: 'not_ready',
        blockers: [
          'independent_taxonomic_verification_missing',
          'reference_support_shortfall',
        ],
      },
      sourceSnapshotSha256: 'b'.repeat(64),
    },
    reviewerControl: null,
    milestone: {
      schemaVersion: 'taxalens-verification-review-milestones:v1.0.0',
      milestonePlanId: 'flickr-quality-milestones',
      decisiveSampleCount: 60,
      status: 'evaluation_due',
      releaseEvaluationAllowed: true,
      currentMilestone: 60,
      nextMilestone: 100,
      evaluatedMilestones: [20, 40],
      missedMilestones: [],
    },
    fingerprints: {
      campaignManifestSha256: '1'.repeat(64),
      questionSha256: '2'.repeat(64),
      samplingPlanSha256: '3'.repeat(64),
      decisionLedgerSha256: '4'.repeat(64),
      reviewedLabelsSha256: '5'.repeat(64),
      referenceReadinessSha256: '6'.repeat(64),
      reviewedLabelLeakageSha256: '7'.repeat(64),
      releasePolicySha256: '8'.repeat(64),
      milestonePlanSha256: '9'.repeat(64),
    },
    release: {
      status: 'release_ready',
      evaluatedAtMilestone: 60,
      blockers: [],
      missingRequiredStrata: [],
    },
    snapshotSha256: 'a'.repeat(64),
  }
}
